config/routes.rb
Geo::Application.routes.draw do
  resources :layers do
    resources :points
    resources :paths
    resources :polygons
  end

  root :to => "layers#index"

end

app/models/point.rb
class Point < ActiveRecord::Base
  # Relations
  belongs_to :layer

  # Validations
  validates :name, :presence => true
  validates :longitude, :numericality => true, :inclusion => { :in => -180..180 }
  validates :latitude, :numericality => true, :inclusion => { :in => -90..90}
  
  include Geometry
end

app/controllers/points_controller.rb
class PointsController < ApplicationController
  before_filter :get_layer
  
  # The before_filter action to get the current layer for
  # for all the points.
  def get_layer
    @layer = Layer.find(params[:layer_id])
  end

  # GET /points.xml
  def index
    @points = @layer.points.all

    respond_to do |format|
      format.html { redirect_to(@layer, :anchor => "points")}
      format.xml  { render :xml => @points }
      format.kml # index.kml.builder
    end
  end

  # GET /points/1
  # GET /points/1.xml
  def show
    @point = Point.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @point }
      format.kml  # show.kml.erb
    end
  end

  # GET /points/new
  # GET /points/new.xml
  def new
    @point = Point.new({:layer => @layer})

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @point }
    end
  end

  # GET /points/1/edit
  def edit
    @point = Point.find(params[:id])
  end

  # POST /points
  # POST /points.xml
  def create
    @point = Point.new(params[:point])

    respond_to do |format|
      if @point.save
        format.html { redirect_to([@layer, @point], :notice => 'Point was successfully created.') }
        format.xml  { render :xml => @point, :status => :created, :location => @point }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @point.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /points/1
  # PUT /points/1.xml
  def update
    @point = Point.find(params[:id])

    respond_to do |format|
      if @point.update_attributes(params[:point])
        format.html { redirect_to([@layer, @point], :notice => 'Point was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @point.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /points/1
  # DELETE /points/1.xml
  def destroy
    @point = Point.find(params[:id])
    @point.destroy

    respond_to do |format|
      format.html { redirect_to(layer_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/points_helper.rb
module PointsHelper

  # Identify the midpoint of a series of points.
  # Uses a center of gravity technique, based off the 
  # cartesian coordinates for each point.
  # Logic from: http://www.geomidpoint.com/calculation.html
  def midpoint(points = [])
    return Point.new(:name => "Midpoint", :latitude => 0, :longitude => 0) if points.empty?
  
    x = y = z = 0
    points.each do |point|
      x += point.x
      y += point.y
      z += point.z
    end
    x, y, z = x/points.length, y/points.length, z/points.length
    longitude = Math.atan2(y, x).radians
    hypotenuse = Math.sqrt(x * x + y * y)
    latitude = Math.atan2(z, hypotenuse).radians
    
    Point.new(:name => "Midpoint", :latitude => latitude, :longitude => longitude)
  end

end

app/views/points/_form.html.erb
<% content_for :js_ready do %>
    <% 
      Point.include_root_in_json = false
    %>
    var point = <%=raw @point.to_json() %>;
    var map = setup_map(point, 10);
    
    var marker = add_point_to_map(point, map, {draggable: true});
        
    google.maps.event.addListener(marker, "drag", function(){
      update_fields(marker.getPosition());
    });
    google.maps.event.addListener(marker, "dragend", function(){
      map.setCenter(marker.getPosition());
    });
<% end %>
<% content_for :js do %>
  function update_fields(latlng){
    $('#point_latitude').val(latlng.lat());
    $('#point_longitude').val(latlng.lng());
  }
<% end %>

<%= form_for([@layer, @point], :html => { :class => 'cmxform'} ) do |f| %>
  <% if @point.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@point.errors.count, "error") %> prohibited this point from being saved:</h2>
    <ul>
    <% @point.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <fieldset>
    <ol>
      <li><%= map_canvas({:style => "height: 300px;"}) %></li>
      <li><%= f.label :name %> <%= f.text_field :name %></li>
      <li><%= f.label :description %>  <%= f.text_area :description %></li>
      <li><%= f.label :layer %> <%= f.collection_select :layer_id, Layer.all, :id, :name %></li>
      <li><%= f.label :latitude %> <%= f.text_field :latitude %></li>
      <li><%= f.label :longitude %> <%= f.text_field :longitude %></li>
    </ol>
  </fieldset>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/points/_index.html.erb
<% if !points.empty? %>
<table cellpadding="0" cellspacing="0" width="100%" class="elements">
 <thead>
	 <tr class="cat_title">
		<th style="text-align:right;">Name</th>
		<th>Center</th>
		<th style="text-align:left;">Description</th>
		<th>Created</th>
		<th>Updated</th>
		<th></th>
	 </tr>
 </thead>
 <tbody>
 <% points.each do |point| %>
 <tr class="<%= cycle('odd', 'even') %>">
  <td><%= link_to [point.layer, point] do %><h2><%= point.name %></h2><% end %></td>
  <td class="center_img"></td>
  <td><p><%=raw point.description %></p></td>
  <td><%= point.created_at.strftime('%D') unless point.created_at.nil? %></td>
  <td><%= point.updated_at.strftime('%D') unless point.updated_at.nil? %></td>
  <td>
    <span>
     <%= link_to 'Edit', edit_layer_point_path(point.layer, point), :class => 'edit-link' %>
     &nbsp;
     <%= link_to 'Remove', layer_point_path(point.layer, point), :confirm => 'Are you sure you want to remove this point?', :method => :delete, :class => 'cancel-link' %>
    </span>
  </td>
 </tr>
 <% end %>
 </tbody>
</table>
<% end %>
<div style="clear:both;"></div>

app/views/points/edit.html.erb
<% content_for :title, "Editing #{@point.name}" %>
<h1 class="main-title">
	Editing Point
	<span><%= link_to 'Cancel and Return', [@layer, @point], :class => 'cancel-link' %></span>
</h1>

<%= render 'form' %>

<%= link_to 'Show', [@layer, @point] %>

app/views/points/new.html.erb
<h1>New <%= @layer.name %> point</h1>

<%= render 'form' %>

<%= link_to 'Back', layer_points_path %>

app/views/points/show.html.erb
<% content_for :js_ready do %>
    <% Point.include_root_in_json = false %>
    var point = <%=raw @point.to_json() %>;
    
    var map = setup_map(point, 13);
    add_point_to_map(point, map);
<% end %>

<% content_for :title, @point.name %>

<h2 class="breadcrumb">
	<%= link_to "Home", root_path %>&nbsp;/&nbsp;
	<%= link_to @layer.name, @layer %>&nbsp;/&nbsp;
</h2>

<div class="main-title">

	<%= @point.name %>
	
	<%= map_canvas({:style => "height: 500px;"})%>
	
	<span>
		<%=raw @point.description %>
		<br />
		Latitude: <%= @point.latitude %>, Longitude: <%= @point.longitude %>
		<br />
		<br />
		<%= link_to 'Edit', edit_layer_point_path(@layer, @point), :class => 'edit-link' %>
		&nbsp;
		<%= link_to 'Remove', layer_point_path(@layer, @point), :confirm => 'Are you sure you want to remove this point?', :method => :delete, :class => 'cancel-link' %>
	</span>
</div>