config/routes.rb
Geo::Application.routes.draw do
  resources :layers do
    resources :points
    resources :paths
    resources :polygons
  end

  root :to => "layers#index"

end

app/models/polygon.rb
class Polygon < ActiveRecord::Base
  #Relations
  belongs_to :layer
  has_many :coords, :as => :line, :dependent => :destroy
  
  # Validations
  validates :name, :presence => true
  
  accepts_nested_attributes_for :coords, :allow_destroy => true
end

app/controllers/polygons_controller.rb
class PolygonsController < ApplicationController
  before_filter :get_layer
  
  # The before_filter action to get the current layer for
  # for all the polygons.
  def get_layer
    @layer = Layer.find(params[:layer_id])
  end

  # GET /polygons.xml
  def index
    @polygons = @layer.polygons.all

    respond_to do |format|
      format.html { redirect_to(@layer, :anchor => "polygons")}
      format.xml  { render :xml => @polygons }
      format.kml # index.kml.builder
    end
  end

  # GET /polygons/1
  # GET /polygons/1.xml
  def show
    @polygon = Polygon.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @polygon }
      format.kml  # show.kml.erb
    end
  end

  # GET /polygons/new
  # GET /polygons/new.xml
  def new
    @polygon = Polygon.new({:layer => @layer})

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @polygon }
    end
  end

  # GET /polygons/1/edit
  def edit
    @polygon = Polygon.find(params[:id])
  end

  # POST /polygons
  # POST /polygons.xml
  def create
    @polygon = Polygon.new(params[:polygon])

    respond_to do |format|
      if @polygon.save
        format.html { redirect_to([@layer, @polygon], :notice => 'Polygon was successfully created.') }
        format.xml  { render :xml => @polygon, :status => :created, :location => @polygon }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @polygon.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /polygons/1
  # PUT /polygons/1.xml
  def update
    @polygon = Polygon.find(params[:id])

    respond_to do |format|
      if @polygon.update_attributes(params[:polygon])
        format.html { redirect_to([@layer, @polygon], :notice => 'Polygon was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @polygon.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /polygons/1
  # DELETE /polygons/1.xml
  def destroy
    @polygon = Polygon.find(params[:id])
    @polygon.destroy

    respond_to do |format|
      format.html { redirect_to(layer_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/polygons_helper.rb
module PolygonsHelper
end

app/views/polygons/_form.html.erb
<% content_for :js_ready do %>
    <% 
      Point.include_root_in_json = false
      Coord.include_root_in_json = false
      point = midpoint(@polygon.coords)
     %>
    var point = <%=raw point.to_json() %>;
    
    map = setup_map(point, 2);
    polygon = new google.maps.Polygon();
    
    polygon.setMap(map);
    
    var coords = <%=raw @polygon.coords.to_json() %>;
    
    $.each(coords, function(index, coord){
      add_point_to_polyobject(coord, polygon);
      add_edit_marker_to_map(coord, index);
    });
    
    //Click to create a new marker.
    google.maps.event.addListener(map, 'click', function(event){
      var next_pos = next_position();
      var index = next_index();
      var coord = {
        latitude: event.latLng.lat(),
        longitude: event.latLng.lng(),
        position: next_position
      };
      add_coord_to_form('polygon', coord, index, '#coord_data');
      add_point_to_polyobject(coord, polygon);
      add_edit_marker_to_map(coord, index);
    });
<% end %>
<% content_for :js do %>
  var map; //The map!
  var polygon; //The line
  var marker_data = new Array();
    
  // Update the polygon with a new position
  // from a marker.
  function update_line(marker, latLng){
    var index = marker_data[marker.get('data_id')].polygon_id;
    polygon.getPath().setAt(index, latLng);
  }
  
  // Add a draggable marker to the map 
  // update a point on a polygon.
  function add_edit_marker_to_map(coord, index){
    var marker = add_point_to_map(coord, map, {draggable: true});
    marker.set('data_id', next_index());
    
    var data = {
      html_id: index, 
      polygon_id: polygon.getPath().length-1,
      active: true,
      marker: marker
    };
    marker_data.push(data);
    
    //Drag to move a marker.
    google.maps.event.addListener(marker, "drag", function(event){
      update_coord_fields('polygon', this, event.latLng);
      update_line(this, event.latLng);
    });
        
    //Right click to delete a marker.
    google.maps.event.addListener(marker, "rightclick", function(event){
      //Remove it from the line and map.
      delete_from_map(this);
      
      //For every active point past the one being deleted
      //decrease its polygon data by one.
      var i = 0;
      var max = marker_data.length;
      for(i = this.get('data_id'); i < max; i++){
        if(marker_data[i].active){
          $('#polygon_coords_attributes_' + i + '_position').val(i);
          marker_data[i].polygon_id--;
        }
      }
      //Remove the position html
      //and replace it with destroy code.
      remove_position_html(this);
    });
    return marker;
  }
  
  // Figure out the position for a new marker.
  function next_position(){
    return $('.coord_position_data').length + 1;
  }
  
  // Figure out the index for a new marker.
  function next_index(){
    return marker_data.length;
  }
  
  // Remove the position input field
  // and replace it with one that will
  // trigger a destroy call.
  function remove_position_html(marker){
    var index = marker_data[marker.get('data_id')].html_id;
    
    var destroy_elem = $('<input>').attr({
      id: 'polygon_coords_attributes_' + index + '__destroy',
      name: 'polygon[coords_attributes][' + index + '][_destroy]',
      value: true,
      type: 'hidden',
      class: 'coord_destroy'
    });
    $('#polygon_coords_attributes_' + index + '_position').replaceWith(destroy_elem);
  }
  
  // Delete the marker from the map
  // and remove the point from the polygon.
  function delete_from_map(marker){
    var index = marker_data[marker.get('data_id')].polygon_id;
    console.log("Deleteing line: " + index);
    polygon.getPath().removeAt(index);
    
    marker.setMap(null);
    
    marker_data[marker.get('data_id')].active = false;
  }
<% end %>

<%= form_for([@layer, @polygon], :html => { :class => 'cmxform'} ) do |f| %>
  <% if @polygon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@polygon.errors.count, "error") %> prohibited this polygon from being saved:</h2>

      <ul>
      <% @polygon.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <fieldset>
    <ol>
      <li><%= map_canvas({:style => "height: 300px;"}) %></li>
      <li><%= f.label :name %> <%= f.text_field :name %></li>
      <li><%= f.label :description %>  <%= f.text_area :description %></li>
      <li><%= f.label :layer %> <%= f.collection_select :layer_id, Layer.all, :id, :name %></li>  
      <div id="coord_data">
        <%= render :partial => 'coords/form', :locals => {:form => f} %>
      </div>
    </ol>
  </fieldset>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/polygons/_index.html.erb
<% if !polygons.empty? %>
<table cellpadding="0" cellspacing="0" width="100%" class="elements">
 <thead>
	 <tr class="cat_title">
		<th style="text-align:right;">Name</th>
		<th>Center</th>
		<th style="text-align:left;">Description</th>
		<th>Created</th>
		<th>Updated</th>
		<th></th>
	 </tr>
 </thead>
 <tbody>
 <% polygons.each do |polygon| %>
 <tr class="<%= cycle('odd', 'even') %>">
  <td><%= link_to [polygon.layer, polygon] do %><h2><%= polygon.name %></h2><% end %></td>
  <td class="center_img"></td>
  <td><p><%=raw polygon.description %></p></td>
  <td><%= polygon.created_at.strftime('%D') unless polygon.created_at.nil? %></td>
  <td><%= polygon.updated_at.strftime('%D') unless polygon.updated_at.nil? %></td>
  <td>
    <span>
     <%= link_to 'Edit', edit_layer_polygon_path(polygon.layer, polygon), :class => 'edit-link' %>
     &nbsp;
     <%= link_to 'Remove', layer_polygon_path(polygon.layer, polygon), :confirm => 'Are you sure you want to remove this polygon?', :method => :delete, :class => 'cancel-link' %>
    </span>
  </td>
 </tr>
 <% end %>
 </tbody>
</table>
<% end %>
<div style="clear:both;"></div>

app/views/polygons/edit.html.erb
<% content_for :title, "Editing #{@polygon.name}" %>
<h1 class="main-title">
	Editing Polygon
	<span><%= link_to 'Cancel and Return', [@layer, @polygon], :class => 'cancel-link' %></span>
</h1>

<%= render 'form' %>

<%= link_to 'Show', [@layer, @polygon] %>

app/views/polygons/new.html.erb
<h1>New polygon</h1>

<%= render 'form' %>

<%= link_to 'Back', layer_polygons_path %>

app/views/polygons/show.html.erb
<% content_for :js_ready do %>
    <% 
      Point.include_root_in_json = false
      Coord.include_root_in_json = false
      point = midpoint(@polygon.coords)
     %>
    var point = <%=raw point.to_json() %>;
    
    var map = setup_map(point, 1);
    var polygon = new google.maps.Polygon();
    var map_bounds = new google.maps.LatLngBounds();
    
    polygon.setMap(map);
    
    var coords = <%=raw @polygon.coords.to_json() %>;
    
    $.each(coords, function(index, coord){
      position = add_point_to_polygon(coord, polygon);
      map_bounds.extend(position);
    });
    map.fitBounds(map_bounds);
<% end %>

<% content_for :title, @polygon.name %>

<h2 class="breadcrumb">
	<%= link_to "Home", root_path %>&nbsp;/&nbsp;
	<%= link_to @layer.name, @layer %>&nbsp;/&nbsp;
</h2>

<div class="main-title">

	<%= @polygon.name %>
	
	<%= map_canvas({:style => " height: 500px;"})%>
	
	<span>
		<%=raw @polygon.description %>
		<br />
		<%= link_to 'Edit', edit_layer_polygon_path(@layer, @polygon), :class => 'edit-link' %>
		&nbsp;
		<%= link_to 'Remove', layer_polygon_path(@layer, @polygon), :confirm => 'Are you sure you want to remove this polygon?', :method => :delete, :class => 'cancel-link' %>
	</span>
</div>