config/routes.rb
Geo::Application.routes.draw do
  resources :layers do
    resources :points
    resources :paths
    resources :polygons
  end

  root :to => "layers#index"

end

app/models/layer.rb
class Layer < ActiveRecord::Base
  # Relations
  has_many :points
  has_many :paths
  has_many :polygons
  
  # Validations
  validates :name, :presence => true
  validates :color, :hex_color => true
end

app/controllers/layers_controller.rb
class LayersController < ApplicationController
  # GET /layers
  # GET /layers.xml
  def index
    @layers = Layer.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @layers }
    end
  end

  # GET /layers/1
  # GET /layers/1.xml
  def show
    @layer = Layer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @layer }
      format.kml  # show.kml.builder
      format.js { render :json => @layer.to_json(
        :include => {
          :points => {}, 
          :paths => {
            :include => { :coords => {
              :only => [:position, :latitude, :longitude]
            }}
          },
          :polygons => {
            :include => { :coords => {
              :only => [:position, :latitude, :longitude]
            }}
          } 
        }
      )}
    end
  end

  # GET /layers/new
  # GET /layers/new.xml
  def new
    @layer = Layer.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @layer }
    end
  end

  # GET /layers/1/edit
  def edit
    @layer = Layer.find(params[:id])
  end

  # POST /layers
  # POST /layers.xml
  def create
    @layer = Layer.new(params[:layer])

    respond_to do |format|
      if @layer.save
        format.html { redirect_to(@layer, :notice => 'Layer was successfully created.') }
        format.xml  { render :xml => @layer, :status => :created, :location => @layer }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @layer.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /layers/1
  # PUT /layers/1.xml
  def update
    @layer = Layer.find(params[:id])

    respond_to do |format|
      if @layer.update_attributes(params[:layer])
        format.html { redirect_to(@layer, :notice => 'Layer was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @layer.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /layers/1
  # DELETE /layers/1.xml
  def destroy
    @layer = Layer.find(params[:id])
    @layer.destroy

    respond_to do |format|
      format.html { redirect_to(layers_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/layers_helper.rb
module LayersHelper

  # Generates a KML color given a hex color string.
  # Converts the format from #RRGGBB to AABBGGRR.
  # The alpha channel defaults to ff.
  def to_kmlcolor(color="#000000", alpha = "ff")
    alpha + color[5,3] + color[3,2] + color[1,2]
  end
end

app/views/layers/_form.html.erb
<%= form_for(@layer, :html => { :class => 'cmxform'} ) do |f| %>
  <% if @layer.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@layer.errors.count, "error") %> prohibited this layer from being saved:</h2>
    <ul>
    <% @layer.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <fieldset>
    <ol>
      <li><%= f.label :name %> <%= f.text_field :name %></li>
      <li><%= f.label :description %>  <%= f.text_area :description %></li>
      <li><%= f.label :color %> <%= f.text_field :color %></li>
    </ol>
  </fieldset>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/layers/edit.html.erb
<% content_for :title, "Editing #{@layer.name}" %>
<h1 class="main-title">
	Editing Layer
	<span><%= link_to 'Cancel and Return', @layer, :class => 'cancel-link' %></span>
</h1>

<%= render 'form' %>

<%= link_to 'Show', @layer %>

app/views/layers/index.html.erb
<h1>Listing layers</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Color</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @layers.each do |layer| %>
  <tr>
    <td><%= layer.name %></td>
    <td><%= layer.description %></td>
    <td><%= layer.color %></td>
    <td><%= link_to 'Show', layer %></td>
    <td><%= link_to 'Edit', edit_layer_path(layer) %></td>
    <td><%= link_to 'Destroy', layer, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Layer', new_layer_path %>

app/views/layers/new.html.erb
<h1>New layer</h1>

<%= render 'form' %>

<%= link_to 'Back', layers_path %>

app/views/layers/show.html.erb
<% content_for :js do %>
  //Global Variables
  var map; //The map!
  var points_on_map; //Total number of objects on the map
<% end %>
<% content_for :js_ready do %>
  <% Point.include_root_in_json = false %>
  var midpoint = <%=raw midpoint(@layer.points).to_json() %>;
  
  map = setup_map(midpoint, 0);
  points_on_map = 0;
  
  $.getJSON('<%= layer_path(:format => :js) %>', function(data) {
    var map_bounds = new google.maps.LatLngBounds();
    $.each(data.layer.points, function(index, point){
      marker = add_point_to_map(point, map);
      map_bounds.extend(marker.position);
      points_on_map++;
    });
    $.each(data.layer.paths, function(index, path){
      var polyline = new google.maps.Polyline();
      polyline.setMap(map);
      
      $.each(path.coords, function(index, coord){
        pos = add_point_to_polyline(coord, polyline);
        map_bounds.extend(pos);
        points_on_map++;
      });
      
    });
    $.each(data.layer.polygons, function(index, polygon_data){
      var polygon = new google.maps.Polygon();
      polygon.setMap(map);
      $.each(polygon_data.coords, function(index, coord){
        add_point_to_polygon(coord, polygon);
        map_bounds.extend(pos);
        points_on_map++;
      });
    });
    if(points_on_map > 1){
      map.fitBounds(map_bounds);
    }
  });
<% end %>

<% content_for :title, @layer.name %>

<h2 class="breadcrumb">
	<%= link_to "Home", root_path %>&nbsp;/&nbsp;
</h2>

<div class="main-title">

	<%= @layer.name %>
	
	<%= map_canvas({:style => " height: 500px;"})%>
	
	<span>
		<%= @layer.description %>
		<br />
		<%= link_to 'Edit', edit_layer_path(@layer), :class => 'edit-link' %>
		&nbsp;
		<%= link_to 'Remove', layer_path(@layer), :confirm => 'Are you sure you want to remove this layer?', :method => :delete, :class => 'cancel-link' %>
	</span>
</div>

<div class="hr_dl flush"><%= image_tag("bl.png", :alt => "") %></div>

<br />

<div class="mc-indent">
	<h2 id="points">Points <%= link_to 'Add', new_layer_point_path(@layer), :class => "link-button" %></h2>
	<div>
	  <%= render :partial => 'points/index', :locals => {:points => @layer.points} %>
	</div>
	<br />
  
  <h2 id="paths">Paths <%= link_to 'Add', new_layer_path_path(@layer), :class => "link-button" %></h2>
	<div>
	  <%= render :partial => 'paths/index', :locals => {:paths => @layer.paths} %>
	</div>
	<br />
	
  <h2 id="polygons">Polygons <%= link_to 'Add', new_layer_polygon_path(@layer), :class => "link-button" %></h2>
	<div>
	  <%= render :partial => 'polygons/index', :locals => {:polygons => @layer.polygons} %>
	</div>
	<br />
	
</div>